INSERT INTO Ciudad (NombreCiudad)
VALUES
('Acayucan'),
('Agua dulce'),
('Altotonga'),
('Alvarado'),
('Ángel R. Cabada'),
('Atoyac'),
('Banderilla'),
('Boca del RÍo'),
('Carlos A. Carrillo'),
('Catemaco'),
('Cazones de Herrera'),
('Cerro Azul'),
('Coatepec'),
('Coatzacoalcos'),
('Coatzintla'),
('Cordoba'),
('Cosamaloapan'),
('Cosoleacaque'),
('Cuichapa'),
('Cuitlahuac'),
('El Higo'),
('Fortin de las Flores'),
('General Miguel Aleman (Potrero Nuevo)'),
('Gutierrez Zamora'),
('Huatusco de Chicuellar'),
('Huayacocotla'),
('Huiloapan de Cuauhtemoc'),
('Isla'),
('Ixtaczoquitlan'),
('Jaltipan de Morelos'),
('Jose Cardel'),
('Juan Diaz Covarrubias'),
('Juan Rodriguez Clara'),
('Las Choapas'),
('Lerdo de Tejada'),
('Minatitlan'),
('Naranjos'),
('Nogales'),
('Orizaba'),
('Panuco'),
('Papantla de Olarte'),
('Paraje Nuevo'),
('Paso del Macho'),
('Paso de Ovejas'),
('Platon Sanchez'),
('Playa Vicente'),
('Poza Rica de Hidalgo'),
('Rio Blanco'),
('San Andres Tuxtla'),
('San Rafael'),
('Santiago Tuxtla'),
('Sihuapan'),
('Soledad de Doblado'),
('Tampico Alto'),
('Tantoyuca'),
('Tempoal de Sanchez'),
('Tezonapa'),
('Tierra Blanca'),
('Tihuatlan'),
('Tlacojalpan'),
('Tlapacoyan'),
('Tres Valles'),
('Tuxpam de Rodriguez Cano'),
('Veracruz'),
('Xalapa-Enriquez'),
('Yecuatla');