INSERT INTO Municipio (name)
VALUES
('Acajete'),
('Acatlan'),
('Acayucan'),
('Actopan'),
('Acula'),
('Acultzingo'),
('Camaron de Tejeda'),
('Alpatlahuac'),
('Alto Lucero de Gutierrez Barrios'),
('Altotonga'),
('Alvarado'),
('Amatitlan'),
('Naranjos Amatlan'),
('Amatlan de los Reyes'),
('Angel R. Cabada'),
('La Antigua'),
('Apazapan'),
('Aquila'),
('Astacinga'),
('Atlahuilco'),
('Atoyac'),
('Atzacan'),
('Atzalan'),
('Tlaltetela'),
('Ayahualulco'),
('Banderilla'),
('Benito Juarez'),
('Boca del Rio'),
('Calcahualco'),
('Camerino Z. Mendoza'),
('Carrillo Puerto'),
('Catemaco'),
('Cazones de Herrera'),
('Cerro Azul'),
('Citlaltepetl'),
('Coacoatzintla'),
('Coahuitlan'),
('Coatepec'),
('Coatzacoalcos'),
('Coatzintla'),
('Coetzala'),
('Colipa'),
('Comapa'),
('Cordoba'),
('Cosamaloapan de Carpio'),
('Cosautlan de Carvajal'),
('Coscomatepec'),
('Cosoleacaque'),
('Cotaxtla'),
('Coxquihui'),
('Coyutla'),
('Cuichapa'),
('Cuitlahuac'),
('Chacaltianguis'),
('Chalma'),
('Chiconamel'),
('Chiconquiaco'),
('Chicontepec'),
('Chinameca'),
('Chinampa de Gorostiza'),
('Las Choapas'),
('Chocaman'),
('Chontla'),
('Chumatlan'),
('Emiliano Zapata'),
('Espinal'),
('Filomeno Mata'),
('Fortin'),
('Gutierrez Zamora'),
('Hidalgotitlan'),
('Huatusco'),
('Huayacocotla'),
('Hueyapan de Ocampo'),
('Huiloapan de Cuauhtemoc'),
('Ignacio de la Llave'),
('Ilamatlan'),
('Isla'),
('Ixcatepec'),
('Ixhuacan de los Reyes'),
('Ixhuatlan del Cafe'),
('Ixhuatlancillo'),
('Ixhuatlan del Sureste'),
('Ixhuatlan de Madero'),
('Ixmatlahuacan'),
('Ixtaczoquitlan'),
('Jalacingo'),
('Xalapa'),
('Jalcomulco'),
('Jaltipan'),
('Jamapa'),
('Jesus Carranza'),
('Xico'),
('Jilotepec'),
('Juan Rodriguez Clara'),
('Juchique de Ferrer'),
('Landero y Coss'),
('Lerdo de Tejada'),
('Magdalena'),
('Maltrata'),
('Manlio Fabio Altamirano'),
('Mariano Escobedo'),
('Martinez de la Torre'),
('Mecatlan'),
('Mecayapan'),
('Medellin de Bravo'),
('Miahuatlan'),
('Las Minas'),
('Minatitlan'),
('Misantla'),
('Mixtla de Altamirano'),
('Moloacan'),
('Naolinco'),
('Naranjal'),
('Nautla'),
('Nogales'),
('Oluta'),
('Omealca'),
('Orizaba'),
('Otatitlan'),
('Oteapan'),
('Ozuluama de Mascareñas'),
('Pajapan'),
('Panuco'),
('Papantla'),
('Paso del Macho'),
('Paso de Ovejas'),
('La Perla'),
('Perote'),
('Platon Sanchez'),
('Playa Vicente'),
('Poza Rica de Hidalgo'),
('Las Vigas de Ramirez'),
('Pueblo Viejo'),
('Puente Nacional'),
('Rafael Delgado'),
('Rafael Lucio'),
('Los Reyes'),
('Rio Blanco'),
('Saltabarranca'),
('San Andres Tenejapan'),
('San Andres Tuxtla'),
('San Juan Evangelista'),
('Santiago Tuxtla'),
('Sayula de Aleman'),
('Soconusco'),
('Sochiapa'),
('Soledad Atzompa'),
('Soledad de Doblado'),
('Soteapan'),
('Tamalin'),
('Tamiahua'),
('Tampico Alto'),
('Tancoco'),
('Tantima'),
('Tantoyuca'),
('Tatatila'),
('Castillo de Teayo'),
('Tecolutla'),
('Tehuipango'),
('Álamo Temapache'),
('Tempoal'),
('Tenampa'),
('Tenochtitlan'),
('Teocelo'),
('Tepatlaxco'),
('Tepetlan'),
('Tepetzintla'),
('Tequila'),
('Jose Azueta'),
('Texcatepec'),
('Texhuacan'),
('Texistepec'),
('Tezonapa'),
('Tierra Blanca'),
('Tihuatlan'),
('Tlacojalpan'),
('Tlacolulan'),
('Tlacotalpan'),
('Tlacotepec de Mejia'),
('Tlachichilco'),
('Tlalixcoyan'),
('Tlalnelhuayocan'),
('Tlapacoyan'),
('Tlaquilpa'),
('Tlilapan'),
('Tomatlan'),
('Tonayan'),
('Totutla'),
('Tuxpan'),
('Tuxtilla'),
('Ursulo Galvan'),
('Vega de Alatorre'),
('Veracruz'),
('Villa Aldama'),
('Xoxocotla'),
('Yanga'),
('Yecuatla'),
('Zacualpan'),
('Zaragoza'),
('Zentla'),
('Zongolica'),
('Zontecomatlan de Lopez y Fuentes'),
('Zozocolco de Hidalgo'),
('Agua Dulce'),
('El Higo'),
('Nanchital de Lazaro Cardenas del Rio'),
('Tres Valles'),
('Carlos A. Carrillo'),
('Tatahuicapan de Juarez'),
('Uxpanapa'),
('San Rafael'),
('Santiago Sochiapan');