
INSERT INTO Ciudad (NombreCiudad)
VALUES
('Acayucan'),
('Agua dulce'),
('Altotonga'),
('Alvarado'),
('Ángel R. Cabada'),
('Atoyac'),
('Banderilla'),
('Boca del RÍo'),
('Carlos A. Carrillo'),
('Catemaco'),
('Cazones de Herrera'),
('Cerro Azul'),
('Coatepec'),
('Coatzacoalcos'),
('Coatzintla'),
('Cordoba'),
('Cosamaloapan'),
('Cosoleacaque'),
('Cuichapa'),
('Cuitlahuac'),
('El Higo'),
('Fortin de las Flores'),
('General Miguel Aleman (Potrero Nuevo)'),
('Gutierrez Zamora'),
('Huatusco de Chicuellar'),
('Huayacocotla'),
('Huiloapan de Cuauhtemoc'),
('Isla'),
('Ixtaczoquitlan'),
('Jaltipan de Morelos'),
('Jose Cardel'),
('Juan Diaz Covarrubias'),
('Juan Rodriguez Clara'),
('Las Choapas'),
('Lerdo de Tejada'),
('Minatitlan'),
('Naranjos'),
('Nogales'),
('Orizaba'),
('Panuco'),
('Papantla de Olarte'),
('Paraje Nuevo'),
('Paso del Macho'),
('Paso de Ovejas'),
('Platon Sanchez'),
('Playa Vicente'),
('Poza Rica de Hidalgo'),
('Rio Blanco'),
('San Andres Tuxtla'),
('San Rafael'),
('Santiago Tuxtla'),
('Sihuapan'),
('Soledad de Doblado'),
('Tampico Alto'),
('Tantoyuca'),
('Tempoal de Sanchez'),
('Tezonapa'),
('Tierra Blanca'),
('Tihuatlan'),
('Tlacojalpan'),
('Tlapacoyan'),
('Tres Valles'),
('Tuxpam de Rodriguez Cano'),
('Veracruz'),
('Xalapa-Enriquez'),
('Yecuatla');

INSERT INTO Municipio (name)
VALUES
('Acajete'),
('Acatlan'),
('Acayucan'),
('Actopan'),
('Acula'),
('Acultzingo'),
('Camaron de Tejeda'),
('Alpatlahuac'),
('Alto Lucero de Gutierrez Barrios'),
('Altotonga'),
('Alvarado'),
('Amatitlan'),
('Naranjos Amatlan'),
('Amatlan de los Reyes'),
('Angel R. Cabada'),
('La Antigua'),
('Apazapan'),
('Aquila'),
('Astacinga'),
('Atlahuilco'),
('Atoyac'),
('Atzacan'),
('Atzalan'),
('Tlaltetela'),
('Ayahualulco'),
('Banderilla'),
('Benito Juarez'),
('Boca del Rio'),
('Calcahualco'),
('Camerino Z. Mendoza'),
('Carrillo Puerto'),
('Catemaco'),
('Cazones de Herrera'),
('Cerro Azul'),
('Citlaltepetl'),
('Coacoatzintla'),
('Coahuitlan'),
('Coatepec'),
('Coatzacoalcos'),
('Coatzintla'),
('Coetzala'),
('Colipa'),
('Comapa'),
('Cordoba'),
('Cosamaloapan de Carpio'),
('Cosautlan de Carvajal'),
('Coscomatepec'),
('Cosoleacaque'),
('Cotaxtla'),
('Coxquihui'),
('Coyutla'),
('Cuichapa'),
('Cuitlahuac'),
('Chacaltianguis'),
('Chalma'),
('Chiconamel'),
('Chiconquiaco'),
('Chicontepec'),
('Chinameca'),
('Chinampa de Gorostiza'),
('Las Choapas'),
('Chocaman'),
('Chontla'),
('Chumatlan'),
('Emiliano Zapata'),
('Espinal'),
('Filomeno Mata'),
('Fortin'),
('Gutierrez Zamora'),
('Hidalgotitlan'),
('Huatusco'),
('Huayacocotla'),
('Hueyapan de Ocampo'),
('Huiloapan de Cuauhtemoc'),
('Ignacio de la Llave'),
('Ilamatlan'),
('Isla'),
('Ixcatepec'),
('Ixhuacan de los Reyes'),
('Ixhuatlan del Cafe'),
('Ixhuatlancillo'),
('Ixhuatlan del Sureste'),
('Ixhuatlan de Madero'),
('Ixmatlahuacan'),
('Ixtaczoquitlan'),
('Jalacingo'),
('Xalapa'),
('Jalcomulco'),
('Jaltipan'),
('Jamapa'),
('Jesus Carranza'),
('Xico'),
('Jilotepec'),
('Juan Rodriguez Clara'),
('Juchique de Ferrer'),
('Landero y Coss'),
('Lerdo de Tejada'),
('Magdalena'),
('Maltrata'),
('Manlio Fabio Altamirano'),
('Mariano Escobedo'),
('Martinez de la Torre'),
('Mecatlan'),
('Mecayapan'),
('Medellin de Bravo'),
('Miahuatlan'),
('Las Minas'),
('Minatitlan'),
('Misantla'),
('Mixtla de Altamirano'),
('Moloacan'),
('Naolinco'),
('Naranjal'),
('Nautla'),
('Nogales'),
('Oluta'),
('Omealca'),
('Orizaba'),
('Otatitlan'),
('Oteapan'),
('Ozuluama de Mascareñas'),
('Pajapan'),
('Panuco'),
('Papantla'),
('Paso del Macho'),
('Paso de Ovejas'),
('La Perla'),
('Perote'),
('Platon Sanchez'),
('Playa Vicente'),
('Poza Rica de Hidalgo'),
('Las Vigas de Ramirez'),
('Pueblo Viejo'),
('Puente Nacional'),
('Rafael Delgado'),
('Rafael Lucio'),
('Los Reyes'),
('Rio Blanco'),
('Saltabarranca'),
('San Andres Tenejapan'),
('San Andres Tuxtla'),
('San Juan Evangelista'),
('Santiago Tuxtla'),
('Sayula de Aleman'),
('Soconusco'),
('Sochiapa'),
('Soledad Atzompa'),
('Soledad de Doblado'),
('Soteapan'),
('Tamalin'),
('Tamiahua'),
('Tampico Alto'),
('Tancoco'),
('Tantima'),
('Tantoyuca'),
('Tatatila'),
('Castillo de Teayo'),
('Tecolutla'),
('Tehuipango'),
('Álamo Temapache'),
('Tempoal'),
('Tenampa'),
('Tenochtitlan'),
('Teocelo'),
('Tepatlaxco'),
('Tepetlan'),
('Tepetzintla'),
('Tequila'),
('Jose Azueta'),
('Texcatepec'),
('Texhuacan'),
('Texistepec'),
('Tezonapa'),
('Tierra Blanca'),
('Tihuatlan'),
('Tlacojalpan'),
('Tlacolulan'),
('Tlacotalpan'),
('Tlacotepec de Mejia'),
('Tlachichilco'),
('Tlalixcoyan'),
('Tlalnelhuayocan'),
('Tlapacoyan'),
('Tlaquilpa'),
('Tlilapan'),
('Tomatlan'),
('Tonayan'),
('Totutla'),
('Tuxpan'),
('Tuxtilla'),
('Ursulo Galvan'),
('Vega de Alatorre'),
('Veracruz'),
('Villa Aldama'),
('Xoxocotla'),
('Yanga'),
('Yecuatla'),
('Zacualpan'),
('Zaragoza'),
('Zentla'),
('Zongolica'),
('Zontecomatlan de Lopez y Fuentes'),
('Zozocolco de Hidalgo'),
('Agua Dulce'),
('El Higo'),
('Nanchital de Lazaro Cardenas del Rio'),
('Tres Valles'),
('Carlos A. Carrillo'),
('Tatahuicapan de Juarez'),
('Uxpanapa'),
('San Rafael'),
('Santiago Sochiapan');

INSERT INTO Estado (NombreEstado)
VALUES
('Veracruz');

INSERT INTO Cliente (name, lastName, phone, calle, colonia, 
nInterior, nExterior, cp, referencias, idMunicipio, idCiudad,
idEstado)
VALUES
('Roberto', 'Lagunes', '2299533808', 'Su calle', 'X colonia', 4, 0,
'76849', 'Referencia', 3, 2, 1);

INSERT INTO Cargo (name)
VALUES
('Administrador'),
('Gerente'),
('Cocinero'),
('Repartidor');

INSERT INTO Empleado (name, lastName, celular, idCargo)
VALUES
('Eduardo', 'Ruiz', '2291289177', 1),
('Lorenzo', 'Alcocer', '2291304567', 1);

INSERT INTO Sucursal (name, calle, colonia, nInterior, nExterior, cp,
idMunicipio, idCiudad, idEstado)
VALUES
('Pizzas ARA', 'Una calle', 'Una colonia', 162, 0, '12345', 1, 2, 1);

INSERT INTO SucursalEmpleado (idSucursal, idEmpleado)
VALUES
(1, 1),
(1, 2);

INSERT INTO Condicion(name) VALUES
('Pendiente'),
('En Preparacion'),
('Enviado'),
('Entregado');

INSERT INTO Orden (idCliente, idSucursal, fecha, idCondicion)
VALUES
(1, 1, CURRENT_TIMESTAMP(2), 1);

INSERT INTO Producto (name, descripcion, precio, quantity)
VALUES
('Hot n Ready', 'Pizza clasica de pepperoni', 89.00, 10),
('Hawaian Chicken', 'Jamon, tocino, pollo y salsa manga habanero', 159.00, 5);

INSERT INTO DetallesOrden (idOrden, idProducto, quantity)
VALUES
(1, 1, 10);
